# ./path
PathAwardId:
  $ref: ./path/awardId.yaml
PathGamePk:
  $ref: ./path/gamePk.yaml
PathPersonId:
  $ref: ./path/personId.yaml
PathSeasonId:
  $ref: ./path/seasonId.yaml
PathSportId:
  $ref: ./path/sportId.yaml
PathTeamId:
  $ref: ./path/teamId.yaml
PathVenueId:
  $ref: ./path/venueId.yaml
PathYearId:
  $ref: ./path/yearId.yaml

# ./query
ActiveStatus:
  $ref: ./query/activeStatus.yaml
Date:
  $ref: ./query/date.yaml
EndDate:
  $ref: ./query/endDate.yaml
Fields:
  $ref: ./query/fields.yaml
Group:
  $ref: ./query/group.yaml
GameTypes:
  $ref: ./query/gameTypes.yaml
QueryGamePk:
  $ref: ./query/gamePk.yaml
Hydrate:
  $ref: ./query/hydrate.yaml
LeagueId:
  $ref: ./query/leagueId.yaml
LeagueIds:
  $ref: ./query/leagueIds.yaml
LeagueListId:
  $ref: ./query/leagueListId.yaml
PersonIds:
  $ref: ./query/personIds.yaml
RosterType:
  $ref: ./query/rosterType.yaml
Season:
  $ref: ./query/season.yaml
SportId:
  $ref: ./query/sportId.yaml
SportIds:
  $ref: ./query/sportIds.yaml
StandingsTypes:
  $ref: ./query/standingsTypes.yaml
Stats:
  $ref: ./query/stats.yaml
StartDate:
  $ref: ./query/startDate.yaml
TeamId:
  $ref: ./query/teamId.yaml
TeamIds:
  $ref: ./query/teams.yaml
Timecode:
  $ref: ./query/timecode.yaml
VenueIds:
  $ref: ./query/venueIds.yaml
