/* tslint:disable */
/* eslint-disable */
/**
 * MLB StatAPI
 * An spec API to consume the MLB Stat API 
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MLBLeague } from './MLBLeague';
import {
    MLBLeagueFromJSON,
    MLBLeagueFromJSONTyped,
    MLBLeagueToJSON,
} from './MLBLeague';
import type { MLBSport } from './MLBSport';
import {
    MLBSportFromJSON,
    MLBSportFromJSONTyped,
    MLBSportToJSON,
} from './MLBSport';

/**
 * Division 
 * 
 * @export
 * @interface MLBDivision
 */
export interface MLBDivision {
    /**
     * 
     * @type {number}
     * @memberof MLBDivision
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof MLBDivision
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof MLBDivision
     */
    season?: string;
    /**
     * 
     * @type {string}
     * @memberof MLBDivision
     */
    nameShort?: string;
    /**
     * 
     * @type {string}
     * @memberof MLBDivision
     */
    link?: string;
    /**
     * 
     * @type {string}
     * @memberof MLBDivision
     */
    abbreviation?: string;
    /**
     * 
     * @type {MLBLeague}
     * @memberof MLBDivision
     */
    league?: MLBLeague;
    /**
     * 
     * @type {MLBSport}
     * @memberof MLBDivision
     */
    sport?: MLBSport;
    /**
     * 
     * @type {boolean}
     * @memberof MLBDivision
     */
    hasWildcard?: boolean;
    /**
     * 
     * @type {number}
     * @memberof MLBDivision
     */
    sortOrder?: number;
    /**
     * 
     * @type {number}
     * @memberof MLBDivision
     */
    numPlayoffTeams?: number;
    /**
     * 
     * @type {boolean}
     * @memberof MLBDivision
     */
    active?: boolean;
}

/**
 * Check if a given object implements the MLBDivision interface.
 */
export function instanceOfMLBDivision(value: object): value is MLBDivision {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function MLBDivisionFromJSON(json: any): MLBDivision {
    return MLBDivisionFromJSONTyped(json, false);
}

export function MLBDivisionFromJSONTyped(json: any, ignoreDiscriminator: boolean): MLBDivision {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'season': json['season'] == null ? undefined : json['season'],
        'nameShort': json['nameShort'] == null ? undefined : json['nameShort'],
        'link': json['link'] == null ? undefined : json['link'],
        'abbreviation': json['abbreviation'] == null ? undefined : json['abbreviation'],
        'league': json['league'] == null ? undefined : MLBLeagueFromJSON(json['league']),
        'sport': json['sport'] == null ? undefined : MLBSportFromJSON(json['sport']),
        'hasWildcard': json['hasWildcard'] == null ? undefined : json['hasWildcard'],
        'sortOrder': json['sortOrder'] == null ? undefined : json['sortOrder'],
        'numPlayoffTeams': json['numPlayoffTeams'] == null ? undefined : json['numPlayoffTeams'],
        'active': json['active'] == null ? undefined : json['active'],
    };
}

export function MLBDivisionToJSON(value?: MLBDivision | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'season': value['season'],
        'nameShort': value['nameShort'],
        'link': value['link'],
        'abbreviation': value['abbreviation'],
        'league': MLBLeagueToJSON(value['league']),
        'sport': MLBSportToJSON(value['sport']),
        'hasWildcard': value['hasWildcard'],
        'sortOrder': value['sortOrder'],
        'numPlayoffTeams': value['numPlayoffTeams'],
        'active': value['active'],
    };
}

