/* tslint:disable */
/* eslint-disable */
/**
 * MLB StatAPI
 * An spec API to consume the MLB Stat API 
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MLBStandings } from './MLBStandings';
import {
    MLBStandingsFromJSON,
    MLBStandingsFromJSONTyped,
    MLBStandingsToJSON,
} from './MLBStandings';

/**
 * 
 * @export
 * @interface MLBStandingsList
 */
export interface MLBStandingsList {
    /**
     * 
     * @type {Array<MLBStandings>}
     * @memberof MLBStandingsList
     */
    records?: Array<MLBStandings>;
}

/**
 * Check if a given object implements the MLBStandingsList interface.
 */
export function instanceOfMLBStandingsList(value: object): value is MLBStandingsList {
    return true;
}

export function MLBStandingsListFromJSON(json: any): MLBStandingsList {
    return MLBStandingsListFromJSONTyped(json, false);
}

export function MLBStandingsListFromJSONTyped(json: any, ignoreDiscriminator: boolean): MLBStandingsList {
    if (json == null) {
        return json;
    }
    return {
        
        'records': json['records'] == null ? undefined : ((json['records'] as Array<any>).map(MLBStandingsFromJSON)),
    };
}

export function MLBStandingsListToJSON(value?: MLBStandingsList | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'records': value['records'] == null ? undefined : ((value['records'] as Array<any>).map(MLBStandingsToJSON)),
    };
}

