/* tslint:disable */
/* eslint-disable */
/**
 * MLB StatAPI
 * An spec API to consume the MLB Stat API 
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MLBTeam } from './MLBTeam';
import {
    MLBTeamFromJSON,
    MLBTeamFromJSONTyped,
    MLBTeamToJSON,
} from './MLBTeam';

/**
 * 
 * @export
 * @interface MLBTeams
 */
export interface MLBTeams {
    /**
     * 
     * @type {Array<MLBTeam>}
     * @memberof MLBTeams
     */
    teams?: Array<MLBTeam>;
}

/**
 * Check if a given object implements the MLBTeams interface.
 */
export function instanceOfMLBTeams(value: object): value is MLBTeams {
    return true;
}

export function MLBTeamsFromJSON(json: any): MLBTeams {
    return MLBTeamsFromJSONTyped(json, false);
}

export function MLBTeamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): MLBTeams {
    if (json == null) {
        return json;
    }
    return {
        
        'teams': json['teams'] == null ? undefined : ((json['teams'] as Array<any>).map(MLBTeamFromJSON)),
    };
}

export function MLBTeamsToJSON(value?: MLBTeams | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'teams': value['teams'] == null ? undefined : ((value['teams'] as Array<any>).map(MLBTeamToJSON)),
    };
}

