/* tslint:disable */
/* eslint-disable */
/**
 * MLB StatAPI
 * An spec API to consume the MLB Stat API 
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Venue
 * 
 * @export
 * @interface MLBVenue
 */
export interface MLBVenue {
    /**
     * 
     * @type {number}
     * @memberof MLBVenue
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof MLBVenue
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof MLBVenue
     */
    link?: string;
    /**
     * 
     * @type {boolean}
     * @memberof MLBVenue
     */
    active?: boolean;
    /**
     * 
     * @type {string}
     * @memberof MLBVenue
     */
    season?: string;
}

/**
 * Check if a given object implements the MLBVenue interface.
 */
export function instanceOfMLBVenue(value: object): value is MLBVenue {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function MLBVenueFromJSON(json: any): MLBVenue {
    return MLBVenueFromJSONTyped(json, false);
}

export function MLBVenueFromJSONTyped(json: any, ignoreDiscriminator: boolean): MLBVenue {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'link': json['link'] == null ? undefined : json['link'],
        'active': json['active'] == null ? undefined : json['active'],
        'season': json['season'] == null ? undefined : json['season'],
    };
}

export function MLBVenueToJSON(value?: MLBVenue | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'link': value['link'],
        'active': value['active'],
        'season': value['season'],
    };
}

