/* tslint:disable */
/* eslint-disable */
/**
 * MLB StatAPI
 * An spec API to consume the MLB Stat API 
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GameContent
 */
export interface GameContent {
    /**
     * 
     * @type {string}
     * @memberof GameContent
     */
    link?: string;
}

/**
 * Check if a given object implements the GameContent interface.
 */
export function instanceOfGameContent(value: object): value is GameContent {
    return true;
}

export function GameContentFromJSON(json: any): GameContent {
    return GameContentFromJSONTyped(json, false);
}

export function GameContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameContent {
    if (json == null) {
        return json;
    }
    return {
        
        'link': json['link'] == null ? undefined : json['link'],
    };
}

export function GameContentToJSON(value?: GameContent | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'link': value['link'],
    };
}

