/* tslint:disable */
/* eslint-disable */
/**
 * MLB StatAPI
 * An spec API to consume the MLB Stat API 
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GameTeam } from './GameTeam';
import {
    GameTeamFromJSON,
    GameTeamFromJSONTyped,
    GameTeamToJSON,
} from './GameTeam';

/**
 * 
 * @export
 * @interface GameTeams
 */
export interface GameTeams {
    /**
     * 
     * @type {GameTeam}
     * @memberof GameTeams
     */
    away: GameTeam;
    /**
     * 
     * @type {GameTeam}
     * @memberof GameTeams
     */
    home: GameTeam;
}

/**
 * Check if a given object implements the GameTeams interface.
 */
export function instanceOfGameTeams(value: object): value is GameTeams {
    if (!('away' in value) || value['away'] === undefined) return false;
    if (!('home' in value) || value['home'] === undefined) return false;
    return true;
}

export function GameTeamsFromJSON(json: any): GameTeams {
    return GameTeamsFromJSONTyped(json, false);
}

export function GameTeamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameTeams {
    if (json == null) {
        return json;
    }
    return {
        
        'away': GameTeamFromJSON(json['away']),
        'home': GameTeamFromJSON(json['home']),
    };
}

export function GameTeamsToJSON(value?: GameTeams | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'away': GameTeamToJSON(value['away']),
        'home': GameTeamToJSON(value['home']),
    };
}

