/* tslint:disable */
/* eslint-disable */
/**
 * MLB StatAPI
 * An spec API to consume the MLB Stat API 
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MLBLeagueDates } from './MLBLeagueDates';
import {
    MLBLeagueDatesFromJSON,
    MLBLeagueDatesFromJSONTyped,
    MLBLeagueDatesToJSON,
} from './MLBLeagueDates';

/**
 * League 
 * 
 * @export
 * @interface League
 */
export interface League {
    /**
     * 
     * @type {number}
     * @memberof League
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof League
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof League
     */
    link?: string;
    /**
     * 
     * @type {string}
     * @memberof League
     */
    abbreviation?: string;
    /**
     * 
     * @type {string}
     * @memberof League
     */
    nameShort?: string;
    /**
     * 
     * @type {string}
     * @memberof League
     */
    seasonState?: string;
    /**
     * 
     * @type {boolean}
     * @memberof League
     */
    hasWildCard?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof League
     */
    hasSplitSeason?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof League
     */
    hasPlayoffPoints?: boolean;
    /**
     * 
     * @type {MLBLeagueDates}
     * @memberof League
     */
    seasonDateInfo?: MLBLeagueDates;
    /**
     * 
     * @type {string}
     * @memberof League
     */
    season?: string;
    /**
     * 
     * @type {string}
     * @memberof League
     */
    orgCode?: string;
    /**
     * 
     * @type {boolean}
     * @memberof League
     */
    conferencesInUse?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof League
     */
    divisionsInUse?: boolean;
    /**
     * 
     * @type {number}
     * @memberof League
     */
    sortOrder?: number;
    /**
     * 
     * @type {boolean}
     * @memberof League
     */
    active?: boolean;
}

/**
 * Check if a given object implements the League interface.
 */
export function instanceOfLeague(value: object): value is League {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function LeagueFromJSON(json: any): League {
    return LeagueFromJSONTyped(json, false);
}

export function LeagueFromJSONTyped(json: any, ignoreDiscriminator: boolean): League {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'link': json['link'] == null ? undefined : json['link'],
        'abbreviation': json['abbreviation'] == null ? undefined : json['abbreviation'],
        'nameShort': json['nameShort'] == null ? undefined : json['nameShort'],
        'seasonState': json['seasonState'] == null ? undefined : json['seasonState'],
        'hasWildCard': json['hasWildCard'] == null ? undefined : json['hasWildCard'],
        'hasSplitSeason': json['hasSplitSeason'] == null ? undefined : json['hasSplitSeason'],
        'hasPlayoffPoints': json['hasPlayoffPoints'] == null ? undefined : json['hasPlayoffPoints'],
        'seasonDateInfo': json['seasonDateInfo'] == null ? undefined : MLBLeagueDatesFromJSON(json['seasonDateInfo']),
        'season': json['season'] == null ? undefined : json['season'],
        'orgCode': json['orgCode'] == null ? undefined : json['orgCode'],
        'conferencesInUse': json['conferencesInUse'] == null ? undefined : json['conferencesInUse'],
        'divisionsInUse': json['divisionsInUse'] == null ? undefined : json['divisionsInUse'],
        'sortOrder': json['sortOrder'] == null ? undefined : json['sortOrder'],
        'active': json['active'] == null ? undefined : json['active'],
    };
}

export function LeagueToJSON(value?: League | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'link': value['link'],
        'abbreviation': value['abbreviation'],
        'nameShort': value['nameShort'],
        'seasonState': value['seasonState'],
        'hasWildCard': value['hasWildCard'],
        'hasSplitSeason': value['hasSplitSeason'],
        'hasPlayoffPoints': value['hasPlayoffPoints'],
        'seasonDateInfo': MLBLeagueDatesToJSON(value['seasonDateInfo']),
        'season': value['season'],
        'orgCode': value['orgCode'],
        'conferencesInUse': value['conferencesInUse'],
        'divisionsInUse': value['divisionsInUse'],
        'sortOrder': value['sortOrder'],
        'active': value['active'],
    };
}

