/* tslint:disable */
/* eslint-disable */
/**
 * MLB StatAPI
 * An spec API to consume the MLB Stat API 
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MLBTeamRecord } from './MLBTeamRecord';
import {
    MLBTeamRecordFromJSON,
    MLBTeamRecordFromJSONTyped,
    MLBTeamRecordToJSON,
} from './MLBTeamRecord';
import type { MLBTeam } from './MLBTeam';
import {
    MLBTeamFromJSON,
    MLBTeamFromJSONTyped,
    MLBTeamToJSON,
} from './MLBTeam';

/**
 * Game Team
 * 
 * @export
 * @interface MLBGameTeam
 */
export interface MLBGameTeam {
    /**
     * 
     * @type {MLBTeamRecord}
     * @memberof MLBGameTeam
     */
    leagueRecord?: MLBTeamRecord;
    /**
     * 
     * @type {number}
     * @memberof MLBGameTeam
     */
    score: number;
    /**
     * 
     * @type {MLBTeam}
     * @memberof MLBGameTeam
     */
    team: MLBTeam;
    /**
     * 
     * @type {boolean}
     * @memberof MLBGameTeam
     */
    isWinner: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MLBGameTeam
     */
    splitSquad?: boolean;
    /**
     * 
     * @type {number}
     * @memberof MLBGameTeam
     */
    seriesNumber?: number;
}

/**
 * Check if a given object implements the MLBGameTeam interface.
 */
export function instanceOfMLBGameTeam(value: object): value is MLBGameTeam {
    if (!('score' in value) || value['score'] === undefined) return false;
    if (!('team' in value) || value['team'] === undefined) return false;
    if (!('isWinner' in value) || value['isWinner'] === undefined) return false;
    return true;
}

export function MLBGameTeamFromJSON(json: any): MLBGameTeam {
    return MLBGameTeamFromJSONTyped(json, false);
}

export function MLBGameTeamFromJSONTyped(json: any, ignoreDiscriminator: boolean): MLBGameTeam {
    if (json == null) {
        return json;
    }
    return {
        
        'leagueRecord': json['leagueRecord'] == null ? undefined : MLBTeamRecordFromJSON(json['leagueRecord']),
        'score': json['score'],
        'team': MLBTeamFromJSON(json['team']),
        'isWinner': json['isWinner'],
        'splitSquad': json['splitSquad'] == null ? undefined : json['splitSquad'],
        'seriesNumber': json['seriesNumber'] == null ? undefined : json['seriesNumber'],
    };
}

export function MLBGameTeamToJSON(value?: MLBGameTeam | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'leagueRecord': MLBTeamRecordToJSON(value['leagueRecord']),
        'score': value['score'],
        'team': MLBTeamToJSON(value['team']),
        'isWinner': value['isWinner'],
        'splitSquad': value['splitSquad'],
        'seriesNumber': value['seriesNumber'],
    };
}

