/* tslint:disable */
/* eslint-disable */
/**
 * MLB StatAPI
 * An spec API to consume the MLB Stat API 
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MLBVenue } from './MLBVenue';
import {
    MLBVenueFromJSON,
    MLBVenueFromJSONTyped,
    MLBVenueToJSON,
} from './MLBVenue';
import type { MLBGameContent } from './MLBGameContent';
import {
    MLBGameContentFromJSON,
    MLBGameContentFromJSONTyped,
    MLBGameContentToJSON,
} from './MLBGameContent';
import type { MLBGameStatus } from './MLBGameStatus';
import {
    MLBGameStatusFromJSON,
    MLBGameStatusFromJSONTyped,
    MLBGameStatusToJSON,
} from './MLBGameStatus';
import type { MLBGameTeams } from './MLBGameTeams';
import {
    MLBGameTeamsFromJSON,
    MLBGameTeamsFromJSONTyped,
    MLBGameTeamsToJSON,
} from './MLBGameTeams';

/**
 * Game
 * 
 * @export
 * @interface MLBGame
 */
export interface MLBGame {
    /**
     * 
     * @type {number}
     * @memberof MLBGame
     */
    gamePk: number;
    /**
     * 
     * @type {string}
     * @memberof MLBGame
     */
    gameGuid: string;
    /**
     * 
     * @type {string}
     * @memberof MLBGame
     */
    link?: string;
    /**
     * Game Type:
     *   * `E` - Exhibition
     *   * `S` - Spring Training
     *   * `R` - Regular Season
     *   * `F` - Wild Card Series
     *   * `D` - Division Series
     *   * `L` - League Championship Series
     *   * `W` - World Series
     * 
     * @type {string}
     * @memberof MLBGame
     */
    gameType: MLBGameGameTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof MLBGame
     */
    season: number;
    /**
     * 
     * @type {string}
     * @memberof MLBGame
     */
    gameDate: string;
    /**
     * 
     * @type {string}
     * @memberof MLBGame
     */
    officialDate: string;
    /**
     * 
     * @type {number}
     * @memberof MLBGame
     */
    rescheduledTo?: number;
    /**
     * 
     * @type {string}
     * @memberof MLBGame
     */
    rescheduledToDate?: string;
    /**
     * 
     * @type {number}
     * @memberof MLBGame
     */
    rescheduledFrom?: number;
    /**
     * 
     * @type {string}
     * @memberof MLBGame
     */
    rescheduledFromDate?: string;
    /**
     * 
     * @type {MLBGameStatus}
     * @memberof MLBGame
     */
    status: MLBGameStatus;
    /**
     * 
     * @type {MLBGameTeams}
     * @memberof MLBGame
     */
    teams: MLBGameTeams;
    /**
     * 
     * @type {MLBVenue}
     * @memberof MLBGame
     */
    venue?: MLBVenue;
    /**
     * 
     * @type {MLBGameContent}
     * @memberof MLBGame
     */
    content?: MLBGameContent;
    /**
     * 
     * @type {boolean}
     * @memberof MLBGame
     */
    isTie?: boolean;
    /**
     * 
     * @type {number}
     * @memberof MLBGame
     */
    gameNumber: number;
    /**
     * 
     * @type {boolean}
     * @memberof MLBGame
     */
    publicFacing?: boolean;
    /**
     * 
     * @type {string}
     * @memberof MLBGame
     */
    doubleHeader?: string;
    /**
     * 
     * @type {string}
     * @memberof MLBGame
     */
    gamedayType?: string;
    /**
     * 
     * @type {string}
     * @memberof MLBGame
     */
    tiebreaker?: string;
    /**
     * 
     * @type {string}
     * @memberof MLBGame
     */
    calendarEventID?: string;
    /**
     * 
     * @type {string}
     * @memberof MLBGame
     */
    seasonDisplay?: string;
    /**
     * 
     * @type {string}
     * @memberof MLBGame
     */
    dayNight?: string;
    /**
     * 
     * @type {string}
     * @memberof MLBGame
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof MLBGame
     */
    scheduledInnings?: number;
    /**
     * 
     * @type {boolean}
     * @memberof MLBGame
     */
    reverseHomeAwayStatus?: boolean;
    /**
     * 
     * @type {number}
     * @memberof MLBGame
     */
    inningBreakLength?: number;
    /**
     * 
     * @type {number}
     * @memberof MLBGame
     */
    gamesInSeries: number;
    /**
     * 
     * @type {number}
     * @memberof MLBGame
     */
    seriesGameNumber: number;
    /**
     * 
     * @type {string}
     * @memberof MLBGame
     */
    seriesDescription?: string;
    /**
     * 
     * @type {string}
     * @memberof MLBGame
     */
    recordSource?: string;
    /**
     * 
     * @type {string}
     * @memberof MLBGame
     */
    ifNecessary?: string;
    /**
     * 
     * @type {string}
     * @memberof MLBGame
     */
    ifNecessaryDescription?: string;
}


/**
 * @export
 */
export const MLBGameGameTypeEnum = {
    Exhibition: 'E',
    SpringTraining: 'S',
    Regular: 'R',
    WildCardSeries: 'F',
    DivisionSeries: 'D',
    LeagueChampionshipSeries: 'L',
    WorldSeries: 'W'
} as const;
export type MLBGameGameTypeEnum = typeof MLBGameGameTypeEnum[keyof typeof MLBGameGameTypeEnum];


/**
 * Check if a given object implements the MLBGame interface.
 */
export function instanceOfMLBGame(value: object): value is MLBGame {
    if (!('gamePk' in value) || value['gamePk'] === undefined) return false;
    if (!('gameGuid' in value) || value['gameGuid'] === undefined) return false;
    if (!('gameType' in value) || value['gameType'] === undefined) return false;
    if (!('season' in value) || value['season'] === undefined) return false;
    if (!('gameDate' in value) || value['gameDate'] === undefined) return false;
    if (!('officialDate' in value) || value['officialDate'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('teams' in value) || value['teams'] === undefined) return false;
    if (!('gameNumber' in value) || value['gameNumber'] === undefined) return false;
    if (!('gamesInSeries' in value) || value['gamesInSeries'] === undefined) return false;
    if (!('seriesGameNumber' in value) || value['seriesGameNumber'] === undefined) return false;
    return true;
}

export function MLBGameFromJSON(json: any): MLBGame {
    return MLBGameFromJSONTyped(json, false);
}

export function MLBGameFromJSONTyped(json: any, ignoreDiscriminator: boolean): MLBGame {
    if (json == null) {
        return json;
    }
    return {
        
        'gamePk': json['gamePk'],
        'gameGuid': json['gameGuid'],
        'link': json['link'] == null ? undefined : json['link'],
        'gameType': json['gameType'],
        'season': json['season'],
        'gameDate': json['gameDate'],
        'officialDate': json['officialDate'],
        'rescheduledTo': json['rescheduledTo'] == null ? undefined : json['rescheduledTo'],
        'rescheduledToDate': json['rescheduledToDate'] == null ? undefined : json['rescheduledToDate'],
        'rescheduledFrom': json['rescheduledFrom'] == null ? undefined : json['rescheduledFrom'],
        'rescheduledFromDate': json['rescheduledFromDate'] == null ? undefined : json['rescheduledFromDate'],
        'status': MLBGameStatusFromJSON(json['status']),
        'teams': MLBGameTeamsFromJSON(json['teams']),
        'venue': json['venue'] == null ? undefined : MLBVenueFromJSON(json['venue']),
        'content': json['content'] == null ? undefined : MLBGameContentFromJSON(json['content']),
        'isTie': json['isTie'] == null ? undefined : json['isTie'],
        'gameNumber': json['gameNumber'],
        'publicFacing': json['publicFacing'] == null ? undefined : json['publicFacing'],
        'doubleHeader': json['doubleHeader'] == null ? undefined : json['doubleHeader'],
        'gamedayType': json['gamedayType'] == null ? undefined : json['gamedayType'],
        'tiebreaker': json['tiebreaker'] == null ? undefined : json['tiebreaker'],
        'calendarEventID': json['calendarEventID'] == null ? undefined : json['calendarEventID'],
        'seasonDisplay': json['seasonDisplay'] == null ? undefined : json['seasonDisplay'],
        'dayNight': json['dayNight'] == null ? undefined : json['dayNight'],
        'description': json['description'] == null ? undefined : json['description'],
        'scheduledInnings': json['scheduledInnings'] == null ? undefined : json['scheduledInnings'],
        'reverseHomeAwayStatus': json['reverseHomeAwayStatus'] == null ? undefined : json['reverseHomeAwayStatus'],
        'inningBreakLength': json['inningBreakLength'] == null ? undefined : json['inningBreakLength'],
        'gamesInSeries': json['gamesInSeries'],
        'seriesGameNumber': json['seriesGameNumber'],
        'seriesDescription': json['seriesDescription'] == null ? undefined : json['seriesDescription'],
        'recordSource': json['recordSource'] == null ? undefined : json['recordSource'],
        'ifNecessary': json['ifNecessary'] == null ? undefined : json['ifNecessary'],
        'ifNecessaryDescription': json['ifNecessaryDescription'] == null ? undefined : json['ifNecessaryDescription'],
    };
}

export function MLBGameToJSON(value?: MLBGame | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'gamePk': value['gamePk'],
        'gameGuid': value['gameGuid'],
        'link': value['link'],
        'gameType': value['gameType'],
        'season': value['season'],
        'gameDate': value['gameDate'],
        'officialDate': value['officialDate'],
        'rescheduledTo': value['rescheduledTo'],
        'rescheduledToDate': value['rescheduledToDate'],
        'rescheduledFrom': value['rescheduledFrom'],
        'rescheduledFromDate': value['rescheduledFromDate'],
        'status': MLBGameStatusToJSON(value['status']),
        'teams': MLBGameTeamsToJSON(value['teams']),
        'venue': MLBVenueToJSON(value['venue']),
        'content': MLBGameContentToJSON(value['content']),
        'isTie': value['isTie'],
        'gameNumber': value['gameNumber'],
        'publicFacing': value['publicFacing'],
        'doubleHeader': value['doubleHeader'],
        'gamedayType': value['gamedayType'],
        'tiebreaker': value['tiebreaker'],
        'calendarEventID': value['calendarEventID'],
        'seasonDisplay': value['seasonDisplay'],
        'dayNight': value['dayNight'],
        'description': value['description'],
        'scheduledInnings': value['scheduledInnings'],
        'reverseHomeAwayStatus': value['reverseHomeAwayStatus'],
        'inningBreakLength': value['inningBreakLength'],
        'gamesInSeries': value['gamesInSeries'],
        'seriesGameNumber': value['seriesGameNumber'],
        'seriesDescription': value['seriesDescription'],
        'recordSource': value['recordSource'],
        'ifNecessary': value['ifNecessary'],
        'ifNecessaryDescription': value['ifNecessaryDescription'],
    };
}

