/* tslint:disable */
/* eslint-disable */
/**
 * MLB StatAPI
 * An spec API to consume the MLB Stat API 
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MLBGameContent
 */
export interface MLBGameContent {
    /**
     * 
     * @type {string}
     * @memberof MLBGameContent
     */
    link?: string;
}

/**
 * Check if a given object implements the MLBGameContent interface.
 */
export function instanceOfMLBGameContent(value: object): value is MLBGameContent {
    return true;
}

export function MLBGameContentFromJSON(json: any): MLBGameContent {
    return MLBGameContentFromJSONTyped(json, false);
}

export function MLBGameContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): MLBGameContent {
    if (json == null) {
        return json;
    }
    return {
        
        'link': json['link'] == null ? undefined : json['link'],
    };
}

export function MLBGameContentToJSON(value?: MLBGameContent | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'link': value['link'],
    };
}

