/* tslint:disable */
/* eslint-disable */
/**
 * MLB StatAPI
 * An spec API to consume the MLB Stat API 
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MLBGameStatus
 */
export interface MLBGameStatus {
    /**
     * 
     * @type {string}
     * @memberof MLBGameStatus
     */
    abstractGameState?: string;
    /**
     * Coded Game State
     *   * `F` - Final
     *   * `D` - Delayed/Postponed
     *   * `S` - Scheduled
     *   * `I` - In Progress
     *   * `P` - Pregame
     *   * `O` - Game Over
     * 
     * @type {string}
     * @memberof MLBGameStatus
     */
    codedGameState?: MLBGameStatusCodedGameStateEnum;
    /**
     * 
     * @type {string}
     * @memberof MLBGameStatus
     */
    detailedState?: string;
    /**
     * 
     * @type {string}
     * @memberof MLBGameStatus
     */
    statusCode?: string;
    /**
     * 
     * @type {boolean}
     * @memberof MLBGameStatus
     */
    startTimeTBD?: boolean;
    /**
     * 
     * @type {string}
     * @memberof MLBGameStatus
     */
    abstractGameCode?: string;
}


/**
 * @export
 */
export const MLBGameStatusCodedGameStateEnum = {
    Final: 'F',
    Postponed: 'D',
    Scheduled: 'S',
    InProgress: 'I',
    Pregame: 'P',
    GameOver: 'O'
} as const;
export type MLBGameStatusCodedGameStateEnum = typeof MLBGameStatusCodedGameStateEnum[keyof typeof MLBGameStatusCodedGameStateEnum];


/**
 * Check if a given object implements the MLBGameStatus interface.
 */
export function instanceOfMLBGameStatus(value: object): value is MLBGameStatus {
    return true;
}

export function MLBGameStatusFromJSON(json: any): MLBGameStatus {
    return MLBGameStatusFromJSONTyped(json, false);
}

export function MLBGameStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): MLBGameStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'abstractGameState': json['abstractGameState'] == null ? undefined : json['abstractGameState'],
        'codedGameState': json['codedGameState'] == null ? undefined : json['codedGameState'],
        'detailedState': json['detailedState'] == null ? undefined : json['detailedState'],
        'statusCode': json['statusCode'] == null ? undefined : json['statusCode'],
        'startTimeTBD': json['startTimeTBD'] == null ? undefined : json['startTimeTBD'],
        'abstractGameCode': json['abstractGameCode'] == null ? undefined : json['abstractGameCode'],
    };
}

export function MLBGameStatusToJSON(value?: MLBGameStatus | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'abstractGameState': value['abstractGameState'],
        'codedGameState': value['codedGameState'],
        'detailedState': value['detailedState'],
        'statusCode': value['statusCode'],
        'startTimeTBD': value['startTimeTBD'],
        'abstractGameCode': value['abstractGameCode'],
    };
}

