/* tslint:disable */
/* eslint-disable */
/**
 * MLB StatAPI
 * An spec API to consume the MLB Stat API 
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MLBGameTeam } from './MLBGameTeam';
import {
    MLBGameTeamFromJSON,
    MLBGameTeamFromJSONTyped,
    MLBGameTeamToJSON,
} from './MLBGameTeam';

/**
 * 
 * @export
 * @interface MLBGameTeams
 */
export interface MLBGameTeams {
    /**
     * 
     * @type {MLBGameTeam}
     * @memberof MLBGameTeams
     */
    away: MLBGameTeam;
    /**
     * 
     * @type {MLBGameTeam}
     * @memberof MLBGameTeams
     */
    home: MLBGameTeam;
}

/**
 * Check if a given object implements the MLBGameTeams interface.
 */
export function instanceOfMLBGameTeams(value: object): value is MLBGameTeams {
    if (!('away' in value) || value['away'] === undefined) return false;
    if (!('home' in value) || value['home'] === undefined) return false;
    return true;
}

export function MLBGameTeamsFromJSON(json: any): MLBGameTeams {
    return MLBGameTeamsFromJSONTyped(json, false);
}

export function MLBGameTeamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): MLBGameTeams {
    if (json == null) {
        return json;
    }
    return {
        
        'away': MLBGameTeamFromJSON(json['away']),
        'home': MLBGameTeamFromJSON(json['home']),
    };
}

export function MLBGameTeamsToJSON(value?: MLBGameTeams | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'away': MLBGameTeamToJSON(value['away']),
        'home': MLBGameTeamToJSON(value['home']),
    };
}

