/* tslint:disable */
/* eslint-disable */
/**
 * MLB StatAPI
 * An spec API to consume the MLB Stat API 
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MLBLeagueRecord
 */
export interface MLBLeagueRecord {
    /**
     * 
     * @type {number}
     * @memberof MLBLeagueRecord
     */
    wins: number;
    /**
     * 
     * @type {number}
     * @memberof MLBLeagueRecord
     */
    losses: number;
    /**
     * 
     * @type {number}
     * @memberof MLBLeagueRecord
     */
    ties?: number;
    /**
     * 
     * @type {string}
     * @memberof MLBLeagueRecord
     */
    pct: string;
}

/**
 * Check if a given object implements the MLBLeagueRecord interface.
 */
export function instanceOfMLBLeagueRecord(value: object): value is MLBLeagueRecord {
    if (!('wins' in value) || value['wins'] === undefined) return false;
    if (!('losses' in value) || value['losses'] === undefined) return false;
    if (!('pct' in value) || value['pct'] === undefined) return false;
    return true;
}

export function MLBLeagueRecordFromJSON(json: any): MLBLeagueRecord {
    return MLBLeagueRecordFromJSONTyped(json, false);
}

export function MLBLeagueRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): MLBLeagueRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'wins': json['wins'],
        'losses': json['losses'],
        'ties': json['ties'] == null ? undefined : json['ties'],
        'pct': json['pct'],
    };
}

export function MLBLeagueRecordToJSON(value?: MLBLeagueRecord | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'wins': value['wins'],
        'losses': value['losses'],
        'ties': value['ties'],
        'pct': value['pct'],
    };
}

