/* tslint:disable */
/* eslint-disable */
/**
 * MLB StatAPI
 * An spec API to consume the MLB Stat API 
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MLBStreak } from './MLBStreak';
import {
    MLBStreakFromJSON,
    MLBStreakFromJSONTyped,
    MLBStreakToJSON,
} from './MLBStreak';
import type { MLBTeam } from './MLBTeam';
import {
    MLBTeamFromJSON,
    MLBTeamFromJSONTyped,
    MLBTeamToJSON,
} from './MLBTeam';
import type { MLBTeamRecord1 } from './MLBTeamRecord1';
import {
    MLBTeamRecord1FromJSON,
    MLBTeamRecord1FromJSONTyped,
    MLBTeamRecord1ToJSON,
} from './MLBTeamRecord1';

/**
 * Record
 * 
 * @export
 * @interface MLBRecord
 */
export interface MLBRecord {
    /**
     * 
     * @type {MLBTeam}
     * @memberof MLBRecord
     */
    team: MLBTeam;
    /**
     * 
     * @type {string}
     * @memberof MLBRecord
     */
    season: string;
    /**
     * 
     * @type {MLBStreak}
     * @memberof MLBRecord
     */
    streak: MLBStreak;
    /**
     * 
     * @type {string}
     * @memberof MLBRecord
     */
    divisionRank: string;
    /**
     * 
     * @type {string}
     * @memberof MLBRecord
     */
    leagueRank: string;
    /**
     * 
     * @type {string}
     * @memberof MLBRecord
     */
    sportRank?: string;
    /**
     * 
     * @type {number}
     * @memberof MLBRecord
     */
    gamesPlayed?: number;
    /**
     * 
     * @type {string}
     * @memberof MLBRecord
     */
    gamesBack: string;
    /**
     * 
     * @type {string}
     * @memberof MLBRecord
     */
    wildCardGamesBack?: string;
    /**
     * 
     * @type {string}
     * @memberof MLBRecord
     */
    leagueGamesBack?: string;
    /**
     * 
     * @type {string}
     * @memberof MLBRecord
     */
    sportGamesBack?: string;
    /**
     * 
     * @type {string}
     * @memberof MLBRecord
     */
    divisionGamesBack?: string;
    /**
     * 
     * @type {string}
     * @memberof MLBRecord
     */
    conferenceGamesBack?: string;
    /**
     * 
     * @type {MLBTeamRecord1}
     * @memberof MLBRecord
     */
    leagueRecord: MLBTeamRecord1;
    /**
     * 
     * @type {string}
     * @memberof MLBRecord
     */
    lastUpdated?: string;
    /**
     * 
     * @type {number}
     * @memberof MLBRecord
     */
    runsAllowed?: number;
    /**
     * 
     * @type {number}
     * @memberof MLBRecord
     */
    runsScored?: number;
    /**
     * 
     * @type {boolean}
     * @memberof MLBRecord
     */
    divisionChamp?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MLBRecord
     */
    divisionLeader?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MLBRecord
     */
    hasWildcard?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MLBRecord
     */
    clinched?: boolean;
    /**
     * 
     * @type {string}
     * @memberof MLBRecord
     */
    eliminationNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof MLBRecord
     */
    eliminationNumberSport?: string;
    /**
     * 
     * @type {string}
     * @memberof MLBRecord
     */
    eliminationNumberLeague?: string;
    /**
     * 
     * @type {string}
     * @memberof MLBRecord
     */
    eliminationNumberDivision?: string;
    /**
     * 
     * @type {string}
     * @memberof MLBRecord
     */
    eliminationNumberConference?: string;
    /**
     * 
     * @type {string}
     * @memberof MLBRecord
     */
    wildCardEliminationNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof MLBRecord
     */
    magicNumber?: string;
    /**
     * 
     * @type {number}
     * @memberof MLBRecord
     */
    wins: number;
    /**
     * 
     * @type {number}
     * @memberof MLBRecord
     */
    losses: number;
    /**
     * 
     * @type {number}
     * @memberof MLBRecord
     */
    runDifferential?: number;
    /**
     * 
     * @type {string}
     * @memberof MLBRecord
     */
    winningPercentage?: string;
}

/**
 * Check if a given object implements the MLBRecord interface.
 */
export function instanceOfMLBRecord(value: object): value is MLBRecord {
    if (!('team' in value) || value['team'] === undefined) return false;
    if (!('season' in value) || value['season'] === undefined) return false;
    if (!('streak' in value) || value['streak'] === undefined) return false;
    if (!('divisionRank' in value) || value['divisionRank'] === undefined) return false;
    if (!('leagueRank' in value) || value['leagueRank'] === undefined) return false;
    if (!('gamesBack' in value) || value['gamesBack'] === undefined) return false;
    if (!('leagueRecord' in value) || value['leagueRecord'] === undefined) return false;
    if (!('wins' in value) || value['wins'] === undefined) return false;
    if (!('losses' in value) || value['losses'] === undefined) return false;
    return true;
}

export function MLBRecordFromJSON(json: any): MLBRecord {
    return MLBRecordFromJSONTyped(json, false);
}

export function MLBRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): MLBRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'team': MLBTeamFromJSON(json['team']),
        'season': json['season'],
        'streak': MLBStreakFromJSON(json['streak']),
        'divisionRank': json['divisionRank'],
        'leagueRank': json['leagueRank'],
        'sportRank': json['sportRank'] == null ? undefined : json['sportRank'],
        'gamesPlayed': json['gamesPlayed'] == null ? undefined : json['gamesPlayed'],
        'gamesBack': json['gamesBack'],
        'wildCardGamesBack': json['wildCardGamesBack'] == null ? undefined : json['wildCardGamesBack'],
        'leagueGamesBack': json['leagueGamesBack'] == null ? undefined : json['leagueGamesBack'],
        'sportGamesBack': json['sportGamesBack'] == null ? undefined : json['sportGamesBack'],
        'divisionGamesBack': json['divisionGamesBack'] == null ? undefined : json['divisionGamesBack'],
        'conferenceGamesBack': json['conferenceGamesBack'] == null ? undefined : json['conferenceGamesBack'],
        'leagueRecord': MLBTeamRecord1FromJSON(json['leagueRecord']),
        'lastUpdated': json['lastUpdated'] == null ? undefined : json['lastUpdated'],
        'runsAllowed': json['runsAllowed'] == null ? undefined : json['runsAllowed'],
        'runsScored': json['runsScored'] == null ? undefined : json['runsScored'],
        'divisionChamp': json['divisionChamp'] == null ? undefined : json['divisionChamp'],
        'divisionLeader': json['divisionLeader'] == null ? undefined : json['divisionLeader'],
        'hasWildcard': json['hasWildcard'] == null ? undefined : json['hasWildcard'],
        'clinched': json['clinched'] == null ? undefined : json['clinched'],
        'eliminationNumber': json['eliminationNumber'] == null ? undefined : json['eliminationNumber'],
        'eliminationNumberSport': json['eliminationNumberSport'] == null ? undefined : json['eliminationNumberSport'],
        'eliminationNumberLeague': json['eliminationNumberLeague'] == null ? undefined : json['eliminationNumberLeague'],
        'eliminationNumberDivision': json['eliminationNumberDivision'] == null ? undefined : json['eliminationNumberDivision'],
        'eliminationNumberConference': json['eliminationNumberConference'] == null ? undefined : json['eliminationNumberConference'],
        'wildCardEliminationNumber': json['wildCardEliminationNumber'] == null ? undefined : json['wildCardEliminationNumber'],
        'magicNumber': json['magicNumber'] == null ? undefined : json['magicNumber'],
        'wins': json['wins'],
        'losses': json['losses'],
        'runDifferential': json['runDifferential'] == null ? undefined : json['runDifferential'],
        'winningPercentage': json['winningPercentage'] == null ? undefined : json['winningPercentage'],
    };
}

export function MLBRecordToJSON(value?: MLBRecord | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'team': MLBTeamToJSON(value['team']),
        'season': value['season'],
        'streak': MLBStreakToJSON(value['streak']),
        'divisionRank': value['divisionRank'],
        'leagueRank': value['leagueRank'],
        'sportRank': value['sportRank'],
        'gamesPlayed': value['gamesPlayed'],
        'gamesBack': value['gamesBack'],
        'wildCardGamesBack': value['wildCardGamesBack'],
        'leagueGamesBack': value['leagueGamesBack'],
        'sportGamesBack': value['sportGamesBack'],
        'divisionGamesBack': value['divisionGamesBack'],
        'conferenceGamesBack': value['conferenceGamesBack'],
        'leagueRecord': MLBTeamRecord1ToJSON(value['leagueRecord']),
        'lastUpdated': value['lastUpdated'],
        'runsAllowed': value['runsAllowed'],
        'runsScored': value['runsScored'],
        'divisionChamp': value['divisionChamp'],
        'divisionLeader': value['divisionLeader'],
        'hasWildcard': value['hasWildcard'],
        'clinched': value['clinched'],
        'eliminationNumber': value['eliminationNumber'],
        'eliminationNumberSport': value['eliminationNumberSport'],
        'eliminationNumberLeague': value['eliminationNumberLeague'],
        'eliminationNumberDivision': value['eliminationNumberDivision'],
        'eliminationNumberConference': value['eliminationNumberConference'],
        'wildCardEliminationNumber': value['wildCardEliminationNumber'],
        'magicNumber': value['magicNumber'],
        'wins': value['wins'],
        'losses': value['losses'],
        'runDifferential': value['runDifferential'],
        'winningPercentage': value['winningPercentage'],
    };
}

