/* tslint:disable */
/* eslint-disable */
/**
 * MLB StatAPI
 * An spec API to consume the MLB Stat API 
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Season
 * 
 * @export
 * @interface MLBSeason
 */
export interface MLBSeason {
    /**
     * 
     * @type {string}
     * @memberof MLBSeason
     */
    seasonId: string;
    /**
     * 
     * @type {boolean}
     * @memberof MLBSeason
     */
    hasWildcard?: boolean;
    /**
     * 
     * @type {string}
     * @memberof MLBSeason
     */
    preSeasonStartDate?: string;
    /**
     * 
     * @type {string}
     * @memberof MLBSeason
     */
    preSeasonEndDate?: string;
    /**
     * 
     * @type {string}
     * @memberof MLBSeason
     */
    seasonStartDate: string;
    /**
     * 
     * @type {string}
     * @memberof MLBSeason
     */
    seasonEndDate: string;
    /**
     * 
     * @type {string}
     * @memberof MLBSeason
     */
    springStartDate?: string;
    /**
     * 
     * @type {string}
     * @memberof MLBSeason
     */
    springEndDate?: string;
    /**
     * 
     * @type {string}
     * @memberof MLBSeason
     */
    regularSeasonStartDate: string;
    /**
     * 
     * @type {string}
     * @memberof MLBSeason
     */
    lastDate1stHalf?: string;
    /**
     * 
     * @type {string}
     * @memberof MLBSeason
     */
    allStartDate?: string;
    /**
     * 
     * @type {string}
     * @memberof MLBSeason
     */
    firstDate2ndHalf?: string;
    /**
     * 
     * @type {string}
     * @memberof MLBSeason
     */
    regularSeasonEndDate: string;
    /**
     * 
     * @type {string}
     * @memberof MLBSeason
     */
    postSeasonStartDate?: string;
    /**
     * 
     * @type {string}
     * @memberof MLBSeason
     */
    postSeasonEndDate?: string;
    /**
     * 
     * @type {string}
     * @memberof MLBSeason
     */
    offSeasonStartDate?: string;
    /**
     * 
     * @type {string}
     * @memberof MLBSeason
     */
    offSeasonEndDate?: string;
    /**
     * 
     * @type {string}
     * @memberof MLBSeason
     */
    seasonLevelGamedayType?: string;
    /**
     * 
     * @type {string}
     * @memberof MLBSeason
     */
    gameLevelGamedayType?: string;
    /**
     * 
     * @type {number}
     * @memberof MLBSeason
     */
    qualifierPlateAppearances?: number;
    /**
     * 
     * @type {number}
     * @memberof MLBSeason
     */
    qualifierOutsPitched?: number;
}

/**
 * Check if a given object implements the MLBSeason interface.
 */
export function instanceOfMLBSeason(value: object): value is MLBSeason {
    if (!('seasonId' in value) || value['seasonId'] === undefined) return false;
    if (!('seasonStartDate' in value) || value['seasonStartDate'] === undefined) return false;
    if (!('seasonEndDate' in value) || value['seasonEndDate'] === undefined) return false;
    if (!('regularSeasonStartDate' in value) || value['regularSeasonStartDate'] === undefined) return false;
    if (!('regularSeasonEndDate' in value) || value['regularSeasonEndDate'] === undefined) return false;
    return true;
}

export function MLBSeasonFromJSON(json: any): MLBSeason {
    return MLBSeasonFromJSONTyped(json, false);
}

export function MLBSeasonFromJSONTyped(json: any, ignoreDiscriminator: boolean): MLBSeason {
    if (json == null) {
        return json;
    }
    return {
        
        'seasonId': json['seasonId'],
        'hasWildcard': json['hasWildcard'] == null ? undefined : json['hasWildcard'],
        'preSeasonStartDate': json['preSeasonStartDate'] == null ? undefined : json['preSeasonStartDate'],
        'preSeasonEndDate': json['preSeasonEndDate'] == null ? undefined : json['preSeasonEndDate'],
        'seasonStartDate': json['seasonStartDate'],
        'seasonEndDate': json['seasonEndDate'],
        'springStartDate': json['springStartDate'] == null ? undefined : json['springStartDate'],
        'springEndDate': json['springEndDate'] == null ? undefined : json['springEndDate'],
        'regularSeasonStartDate': json['regularSeasonStartDate'],
        'lastDate1stHalf': json['lastDate1stHalf'] == null ? undefined : json['lastDate1stHalf'],
        'allStartDate': json['allStartDate'] == null ? undefined : json['allStartDate'],
        'firstDate2ndHalf': json['firstDate2ndHalf'] == null ? undefined : json['firstDate2ndHalf'],
        'regularSeasonEndDate': json['regularSeasonEndDate'],
        'postSeasonStartDate': json['postSeasonStartDate'] == null ? undefined : json['postSeasonStartDate'],
        'postSeasonEndDate': json['postSeasonEndDate'] == null ? undefined : json['postSeasonEndDate'],
        'offSeasonStartDate': json['offSeasonStartDate'] == null ? undefined : json['offSeasonStartDate'],
        'offSeasonEndDate': json['offSeasonEndDate'] == null ? undefined : json['offSeasonEndDate'],
        'seasonLevelGamedayType': json['seasonLevelGamedayType'] == null ? undefined : json['seasonLevelGamedayType'],
        'gameLevelGamedayType': json['gameLevelGamedayType'] == null ? undefined : json['gameLevelGamedayType'],
        'qualifierPlateAppearances': json['qualifierPlateAppearances'] == null ? undefined : json['qualifierPlateAppearances'],
        'qualifierOutsPitched': json['qualifierOutsPitched'] == null ? undefined : json['qualifierOutsPitched'],
    };
}

export function MLBSeasonToJSON(value?: MLBSeason | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'seasonId': value['seasonId'],
        'hasWildcard': value['hasWildcard'],
        'preSeasonStartDate': value['preSeasonStartDate'],
        'preSeasonEndDate': value['preSeasonEndDate'],
        'seasonStartDate': value['seasonStartDate'],
        'seasonEndDate': value['seasonEndDate'],
        'springStartDate': value['springStartDate'],
        'springEndDate': value['springEndDate'],
        'regularSeasonStartDate': value['regularSeasonStartDate'],
        'lastDate1stHalf': value['lastDate1stHalf'],
        'allStartDate': value['allStartDate'],
        'firstDate2ndHalf': value['firstDate2ndHalf'],
        'regularSeasonEndDate': value['regularSeasonEndDate'],
        'postSeasonStartDate': value['postSeasonStartDate'],
        'postSeasonEndDate': value['postSeasonEndDate'],
        'offSeasonStartDate': value['offSeasonStartDate'],
        'offSeasonEndDate': value['offSeasonEndDate'],
        'seasonLevelGamedayType': value['seasonLevelGamedayType'],
        'gameLevelGamedayType': value['gameLevelGamedayType'],
        'qualifierPlateAppearances': value['qualifierPlateAppearances'],
        'qualifierOutsPitched': value['qualifierOutsPitched'],
    };
}

