/* tslint:disable */
/* eslint-disable */
/**
 * MLB StatAPI
 * An spec API to consume the MLB Stat API 
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MLBSeason } from './MLBSeason';
import {
    MLBSeasonFromJSON,
    MLBSeasonFromJSONTyped,
    MLBSeasonToJSON,
} from './MLBSeason';

/**
 * 
 * @export
 * @interface MLBSeasons
 */
export interface MLBSeasons {
    /**
     * 
     * @type {Array<MLBSeason>}
     * @memberof MLBSeasons
     */
    seasons?: Array<MLBSeason>;
}

/**
 * Check if a given object implements the MLBSeasons interface.
 */
export function instanceOfMLBSeasons(value: object): value is MLBSeasons {
    return true;
}

export function MLBSeasonsFromJSON(json: any): MLBSeasons {
    return MLBSeasonsFromJSONTyped(json, false);
}

export function MLBSeasonsFromJSONTyped(json: any, ignoreDiscriminator: boolean): MLBSeasons {
    if (json == null) {
        return json;
    }
    return {
        
        'seasons': json['seasons'] == null ? undefined : ((json['seasons'] as Array<any>).map(MLBSeasonFromJSON)),
    };
}

export function MLBSeasonsToJSON(value?: MLBSeasons | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'seasons': value['seasons'] == null ? undefined : ((value['seasons'] as Array<any>).map(MLBSeasonToJSON)),
    };
}

