/* tslint:disable */
/* eslint-disable */
/**
 * MLB StatAPI
 * An spec API to consume the MLB Stat API 
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MLBScheduleDay } from './MLBScheduleDay';
import {
    MLBScheduleDayFromJSON,
    MLBScheduleDayFromJSONTyped,
    MLBScheduleDayToJSON,
} from './MLBScheduleDay';

/**
 * Schedule
 * 
 * @export
 * @interface MLBSchedule
 */
export interface MLBSchedule {
    /**
     * 
     * @type {number}
     * @memberof MLBSchedule
     */
    totalItems: number;
    /**
     * 
     * @type {number}
     * @memberof MLBSchedule
     */
    totalEvents: number;
    /**
     * 
     * @type {number}
     * @memberof MLBSchedule
     */
    totalGames: number;
    /**
     * 
     * @type {number}
     * @memberof MLBSchedule
     */
    totalGamesInProgress: number;
    /**
     * 
     * @type {Array<MLBScheduleDay>}
     * @memberof MLBSchedule
     */
    dates: Array<MLBScheduleDay>;
}

/**
 * Check if a given object implements the MLBSchedule interface.
 */
export function instanceOfMLBSchedule(value: object): value is MLBSchedule {
    if (!('totalItems' in value) || value['totalItems'] === undefined) return false;
    if (!('totalEvents' in value) || value['totalEvents'] === undefined) return false;
    if (!('totalGames' in value) || value['totalGames'] === undefined) return false;
    if (!('totalGamesInProgress' in value) || value['totalGamesInProgress'] === undefined) return false;
    if (!('dates' in value) || value['dates'] === undefined) return false;
    return true;
}

export function MLBScheduleFromJSON(json: any): MLBSchedule {
    return MLBScheduleFromJSONTyped(json, false);
}

export function MLBScheduleFromJSONTyped(json: any, ignoreDiscriminator: boolean): MLBSchedule {
    if (json == null) {
        return json;
    }
    return {
        
        'totalItems': json['totalItems'],
        'totalEvents': json['totalEvents'],
        'totalGames': json['totalGames'],
        'totalGamesInProgress': json['totalGamesInProgress'],
        'dates': ((json['dates'] as Array<any>).map(MLBScheduleDayFromJSON)),
    };
}

export function MLBScheduleToJSON(value?: MLBSchedule | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'totalItems': value['totalItems'],
        'totalEvents': value['totalEvents'],
        'totalGames': value['totalGames'],
        'totalGamesInProgress': value['totalGamesInProgress'],
        'dates': ((value['dates'] as Array<any>).map(MLBScheduleDayToJSON)),
    };
}

