/* tslint:disable */
/* eslint-disable */
/**
 * MLB StatAPI
 * An spec API to consume the MLB Stat API 
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MLBStreak
 */
export interface MLBStreak {
    /**
     * Streak Type:
     *   * Losing Streak
     *   * Winning Streak
     * 
     * @type {string}
     * @memberof MLBStreak
     */
    streakType?: MLBStreakStreakTypeEnum;
}


/**
 * @export
 */
export const MLBStreakStreakTypeEnum = {
    Losing: 'losses',
    Winning: 'wins'
} as const;
export type MLBStreakStreakTypeEnum = typeof MLBStreakStreakTypeEnum[keyof typeof MLBStreakStreakTypeEnum];


/**
 * Check if a given object implements the MLBStreak interface.
 */
export function instanceOfMLBStreak(value: object): value is MLBStreak {
    return true;
}

export function MLBStreakFromJSON(json: any): MLBStreak {
    return MLBStreakFromJSONTyped(json, false);
}

export function MLBStreakFromJSONTyped(json: any, ignoreDiscriminator: boolean): MLBStreak {
    if (json == null) {
        return json;
    }
    return {
        
        'streakType': json['streakType'] == null ? undefined : json['streakType'],
    };
}

export function MLBStreakToJSON(value?: MLBStreak | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'streakType': value['streakType'],
    };
}

