/* tslint:disable */
/* eslint-disable */
/**
 * MLB StatAPI
 * An spec API to consume the MLB Stat API 
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MLBTeamRecord
 */
export interface MLBTeamRecord {
    /**
     * 
     * @type {number}
     * @memberof MLBTeamRecord
     */
    wins?: number;
    /**
     * 
     * @type {number}
     * @memberof MLBTeamRecord
     */
    losses?: number;
    /**
     * 
     * @type {string}
     * @memberof MLBTeamRecord
     */
    pct?: string;
}

/**
 * Check if a given object implements the MLBTeamRecord interface.
 */
export function instanceOfMLBTeamRecord(value: object): value is MLBTeamRecord {
    return true;
}

export function MLBTeamRecordFromJSON(json: any): MLBTeamRecord {
    return MLBTeamRecordFromJSONTyped(json, false);
}

export function MLBTeamRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): MLBTeamRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'wins': json['wins'] == null ? undefined : json['wins'],
        'losses': json['losses'] == null ? undefined : json['losses'],
        'pct': json['pct'] == null ? undefined : json['pct'],
    };
}

export function MLBTeamRecordToJSON(value?: MLBTeamRecord | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'wins': value['wins'],
        'losses': value['losses'],
        'pct': value['pct'],
    };
}

