/* tslint:disable */
/* eslint-disable */
/**
 * MLB StatAPI
 * An spec API to consume the MLB Stat API 
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MLBScheduleDay } from './MLBScheduleDay';
import {
    MLBScheduleDayFromJSON,
    MLBScheduleDayFromJSONTyped,
    MLBScheduleDayToJSON,
} from './MLBScheduleDay';

/**
 * Schedule
 * 
 * @export
 * @interface Schedule
 */
export interface Schedule {
    /**
     * 
     * @type {number}
     * @memberof Schedule
     */
    totalItems: number;
    /**
     * 
     * @type {number}
     * @memberof Schedule
     */
    totalEvents: number;
    /**
     * 
     * @type {number}
     * @memberof Schedule
     */
    totalGames: number;
    /**
     * 
     * @type {number}
     * @memberof Schedule
     */
    totalGamesInProgress: number;
    /**
     * 
     * @type {Array<MLBScheduleDay>}
     * @memberof Schedule
     */
    dates: Array<MLBScheduleDay>;
}

/**
 * Check if a given object implements the Schedule interface.
 */
export function instanceOfSchedule(value: object): value is Schedule {
    if (!('totalItems' in value) || value['totalItems'] === undefined) return false;
    if (!('totalEvents' in value) || value['totalEvents'] === undefined) return false;
    if (!('totalGames' in value) || value['totalGames'] === undefined) return false;
    if (!('totalGamesInProgress' in value) || value['totalGamesInProgress'] === undefined) return false;
    if (!('dates' in value) || value['dates'] === undefined) return false;
    return true;
}

export function ScheduleFromJSON(json: any): Schedule {
    return ScheduleFromJSONTyped(json, false);
}

export function ScheduleFromJSONTyped(json: any, ignoreDiscriminator: boolean): Schedule {
    if (json == null) {
        return json;
    }
    return {
        
        'totalItems': json['totalItems'],
        'totalEvents': json['totalEvents'],
        'totalGames': json['totalGames'],
        'totalGamesInProgress': json['totalGamesInProgress'],
        'dates': ((json['dates'] as Array<any>).map(MLBScheduleDayFromJSON)),
    };
}

export function ScheduleToJSON(value?: Schedule | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'totalItems': value['totalItems'],
        'totalEvents': value['totalEvents'],
        'totalGames': value['totalGames'],
        'totalGamesInProgress': value['totalGamesInProgress'],
        'dates': ((value['dates'] as Array<any>).map(MLBScheduleDayToJSON)),
    };
}

